version: '3.4'

services:
  #AccountAPI
  simbir.health.accountapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_accountservice:1.0
    container_name: Simbir.Health.AccountAPI
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.AccountAPI/Dockerfile
    restart: unless-stopped
  #DocumentAPI
  simbir.health.documentapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_documentservice:1.0
    container_name: Simbir.Health.DocumentAPI
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.DocumentAPI/Dockerfile
    restart: unless-stopped
  #HospitalAPI
  simbir.health.hospitalapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_hospitalservice:1.0
    container_name: Simbir.Health.HospitalAPI
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.HospitalAPI/Dockerfile
    restart: unless-stopped
  #TimetableAPI
  simbir.health.timetableapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_timetableservice:1.0
    container_name: Simbir.Health.TimetableAPI
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.TimetableAPI/Dockerfile
    restart: unless-stopped
  #PostgreSQL
  postgres_db:
    image: postgres:17.0-bookworm
    container_name: Simbir.Health.PostgreSQL
    environment:
        POSTGRES_DB: "simbirhealth"
        POSTGRES_USER: "volgait_practice"
        POSTGRES_PASSWORD: "root"
    ports:
      - "5432:80"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  #

  #PgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: Simbir.Health.PgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: qwerty11ert@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Werty11ert
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db
  #

  #Redis
  redis_cache:
    image: redis:7.4-bookworm
    container_name: Simbir.Health.Redis
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=admin
      - REDIS_USER_PASSWORD=admin
    ports:
      - "6380:6379"
    volumes:
      - ./redis_cache:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "root", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
  #

  # #RabbitMQ
  # rabbitmq_broker:
  #   image: rabbitmq:3-management
  #   container_name: Simbir.Health.RabbitMQ
  #   hostname: rabbitmq
  #   restart: always
  #   volumes:
  #     - ./rabbitmq_data:/var/lib/rabbitmq
  #     - ./rabbitmq_data:/var/log/rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  # #
volumes:
  postgres_data:
  pgadmin_data:
  # rabbitmq_broker:  
  redis_cache:  