version: '3.4'

services:
  simbir.health.accountapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_microservices
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.AccountAPI/Dockerfile
  simbir.health.documentapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_microservices
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.DocumentAPI/Dockerfile
  simbir.health.hospitalapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_microservices
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.HospitalAPI/Dockerfile
  simbir.health.timetableapi:
    image: ${DOCKER_REGISTRY-}simbirhealth_microservices
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Simbir.Health.TimetableAPI/Dockerfile
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
        POSTGRES_DB: "simbirhealth"
      # PostgreSQL username
        POSTGRES_USER: "volgait_practice"
      # SPostgreSQL password
        POSTGRES_PASSWORD: "root"
    ports:
      - "5432:80"
    volumes:
      # Mount a volume to persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      # Default email for pgAdmin 4
      PGADMIN_DEFAULT_EMAIL: qwerty11ert@gmail.com
      # Password for pgAdmin 4
      PGADMIN_DEFAULT_PASSWORD: Werty11ert
    ports:
      # Map host port 5050 to container port 80
      - "5050:80"
    volumes:
      # Mount a volume to persist pgAdmin 4 data
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      # Ensure that this service starts after 'db'
      - postgres_db
volumes:
  # volume for PostgreSQL
  postgres_data:
  # Volume for pgAdmin 4
  pgadmin_data: