// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simbir.Health.AccountAPI.Model;

#nullable disable

namespace Simbir.Health.AccountAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241101081451_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simbir.Health.AccountAPI.Model.Database.DBO.UsersTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string[]>("roles")
                        .HasColumnType("text[]");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("userTableObj");

                    b.HasData(
                        new
                        {
                            id = 1,
                            firstName = "Администратор",
                            password = "admin",
                            roles = new[] { "Admin" },
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            firstName = "Менеджер",
                            password = "manager",
                            roles = new[] { "Manager" },
                            username = "manager"
                        },
                        new
                        {
                            id = 3,
                            firstName = "Доктор",
                            password = "doctor",
                            roles = new[] { "Doctor" },
                            username = "doctor"
                        },
                        new
                        {
                            id = 4,
                            firstName = "Пользователь",
                            password = "user",
                            roles = new[] { "User" },
                            username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
